name: pending_bill_plugin
description: Headless access to pending bill data for background Flutter engines.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.rkroom.pending_bill_plugin
        pluginClass: PendingBillPlugin
