-keep class net.sqlcipher.** { *; }
-keepnames interface com.rkroom.simple_account.ExtractionStrategy
-keepnames interface com.rkroom.simple_account.ConcatPart
-keepnames class * implements com.rkroom.simple_account.ExtractionStrategy
-keepnames class * implements com.rkroom.simple_account.ConcatPart
-keepnames class com.rkroom.simple_account.RuleDetail
-keepnames class com.rkroom.simple_account.ExtractionRule