name: Build Android App

on: [push,workflow_dispatch]

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@main
        
      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@main
        with:
          channel: stable
          cache: true

      - name: Generate debug keystore
        run: |
          mkdir $env:USERPROFILE\.android
          keytool -genkeypair `
            -alias androiddebugkey `
            -keypass android `
            -keystore $env:USERPROFILE\.android\debug.keystore `
            -storepass android `
            -dname "CN=Android Debug,O=Android" `
            -validity 10000 `
            -keyalg RSA `
            -keysize 3072
            
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@main
        with:
          name: simple_account
          path: build\app\outputs\flutter-apk\**